/**
 * RentalObster Escrow — TypeScript client
 *
 * Provides instruction builders and PDA derivation for the
 * rentalobster_escrow Anchor program, using only @solana/web3.js
 * (no @coral-xyz/anchor dependency required on the frontend).
 *
 * Instruction discriminators are computed at runtime using the Web Crypto API
 * (sha256("global:<instruction_name>")[0..8]) — identical to what Anchor generates.
 *
 * Account layout for each instruction is documented in lib.rs.
 */

import {
  PublicKey,
  SystemProgram,
  TransactionInstruction,
  Connection,
  Transaction,
  Keypair,
  sendAndConfirmTransaction,
} from "@solana/web3.js";

// ─── Program ID ───────────────────────────────────────────────────────────────

export function getEscrowProgramId(): PublicKey | null {
  const id = process.env.NEXT_PUBLIC_ESCROW_PROGRAM_ID;
  if (!id || id === "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS") return null;
  try { return new PublicKey(id); } catch { return null; }
}

// ─── PDA seeds ────────────────────────────────────────────────────────────────

const CONFIG_SEED  = Buffer.from("ro_config");
const ESCROW_SEED  = Buffer.from("ro_escrow");
const VAULT_SEED   = Buffer.from("ro_vault");

export function findConfigPDA(programId: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync([CONFIG_SEED], programId);
}

export function findEscrowPDA(
  renter: PublicKey,
  nonce: Uint8Array,
  programId: PublicKey,
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [ESCROW_SEED, renter.toBytes(), nonce],
    programId,
  );
}

export function findVaultPDA(
  escrowKey: PublicKey,
  programId: PublicKey,
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [VAULT_SEED, escrowKey.toBytes()],
    programId,
  );
}

// ─── Instruction discriminators (sha256("global:<name>")[0..8]) ───────────────

const _discCache: Record<string, Uint8Array> = {};

async function disc(ixName: string): Promise<Uint8Array> {
  if (_discCache[ixName]) return _discCache[ixName];
  const preimage = new TextEncoder().encode(`global:${ixName}`);
  const hash = await globalThis.crypto.subtle.digest("SHA-256", preimage as unknown as ArrayBuffer);
  const d = new Uint8Array(hash, 0, 8);
  _discCache[ixName] = d;
  return d;
}

// ─── Borsh helpers ────────────────────────────────────────────────────────────

function writeU64LE(buf: Buffer, value: bigint, offset: number): void {
  buf.writeBigUInt64LE(value, offset);
}

// ─── Instruction: initialize ──────────────────────────────────────────────────
// Call once after deployment. Signer = platform authority.
// Accounts: config (init), authority (signer, payer), system_program

export async function buildInitializeIx(
  programId: PublicKey,
  authority: PublicKey,
  treasury: PublicKey,
): Promise<TransactionInstruction> {
  const [configPDA] = findConfigPDA(programId);
  const d = await disc("initialize");

  // args: treasury (Pubkey = 32 bytes)
  const data = Buffer.alloc(8 + 32);
  Buffer.from(d).copy(data, 0);
  Buffer.from(treasury.toBytes()).copy(data, 8);

  return new TransactionInstruction({
    programId,
    keys: [
      { pubkey: configPDA,               isSigner: false, isWritable: true },
      { pubkey: authority,               isSigner: true,  isWritable: true },
      { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
    ],
    data,
  });
}

// ─── Instruction: create_rental ───────────────────────────────────────────────
// Renter calls this to lock SOL in the vault PDA.
// Args: nonce [u8;8], amount_lamports u64, platform_fee_lamports u64, agent_owner Pubkey
// Accounts: escrow (init), vault (mut), renter (signer, payer), system_program

export async function buildCreateRentalIx(
  programId: PublicKey,
  renter: PublicKey,
  agentOwner: PublicKey,
  nonce: Uint8Array,          // random 8 bytes, generated by the frontend
  amountLamports: bigint,     // agent owner's cut
  platformFeeLamports: bigint,
): Promise<TransactionInstruction> {
  const [escrowPDA]  = findEscrowPDA(renter, nonce, programId);
  const [vaultPDA]   = findVaultPDA(escrowPDA, programId);
  const d = await disc("create_rental");

  // args: nonce (8) + amount (8) + fee (8) + agent_owner (32) = 56 bytes
  const data = Buffer.alloc(8 + 56);
  Buffer.from(d).copy(data, 0);
  Buffer.from(nonce).copy(data, 8);
  writeU64LE(data, amountLamports, 16);
  writeU64LE(data, platformFeeLamports, 24);
  Buffer.from(agentOwner.toBytes()).copy(data, 32);

  return new TransactionInstruction({
    programId,
    keys: [
      { pubkey: escrowPDA,               isSigner: false, isWritable: true  }, // 0. escrow
      { pubkey: vaultPDA,                isSigner: false, isWritable: true  }, // 1. vault
      { pubkey: renter,                  isSigner: true,  isWritable: true  }, // 2. renter
      { pubkey: SystemProgram.programId, isSigner: false, isWritable: false }, // 3. system_program
    ],
    data,
  });
}

// ─── Instruction: complete_rental ─────────────────────────────────────────────
// Releases funds: agent_owner gets amount, treasury gets fee.
// Signer: renter or platform authority.
// Accounts: config, escrow (mut), vault (mut), agent_owner (mut),
//           treasury (mut), signer, system_program

export async function buildCompleteRentalIx(
  programId: PublicKey,
  escrowPubkey: PublicKey,
  agentOwner: PublicKey,
  treasury: PublicKey,
  signer: PublicKey,
  // needed to re-derive vault PDA
  vaultBump?: number,
): Promise<TransactionInstruction> {
  const [configPDA] = findConfigPDA(programId);
  const [vaultPDA]  = findVaultPDA(escrowPubkey, programId);
  const d = await disc("complete_rental");

  const data = Buffer.alloc(8); // no args
  Buffer.from(d).copy(data, 0);

  return new TransactionInstruction({
    programId,
    keys: [
      { pubkey: configPDA,               isSigner: false, isWritable: false }, // 0. config
      { pubkey: escrowPubkey,            isSigner: false, isWritable: true  }, // 1. escrow
      { pubkey: vaultPDA,                isSigner: false, isWritable: true  }, // 2. vault
      { pubkey: agentOwner,              isSigner: false, isWritable: true  }, // 3. agent_owner
      { pubkey: treasury,                isSigner: false, isWritable: true  }, // 4. treasury
      { pubkey: signer,                  isSigner: true,  isWritable: false }, // 5. signer
      { pubkey: SystemProgram.programId, isSigner: false, isWritable: false }, // 6. system_program
    ],
    data,
  });
}

// ─── Instruction: refund_rental ───────────────────────────────────────────────
// Refunds all SOL to renter. Authority only.
// Accounts: config, escrow (mut), vault (mut), renter (mut), authority (signer), system_program

export async function buildRefundRentalIx(
  programId: PublicKey,
  escrowPubkey: PublicKey,
  renter: PublicKey,
  authority: PublicKey,
): Promise<TransactionInstruction> {
  const [configPDA] = findConfigPDA(programId);
  const [vaultPDA]  = findVaultPDA(escrowPubkey, programId);
  const d = await disc("refund_rental");

  const data = Buffer.alloc(8);
  Buffer.from(d).copy(data, 0);

  return new TransactionInstruction({
    programId,
    keys: [
      { pubkey: configPDA,               isSigner: false, isWritable: false }, // 0. config
      { pubkey: escrowPubkey,            isSigner: false, isWritable: true  }, // 1. escrow
      { pubkey: vaultPDA,                isSigner: false, isWritable: true  }, // 2. vault
      { pubkey: renter,                  isSigner: false, isWritable: true  }, // 3. renter
      { pubkey: authority,               isSigner: true,  isWritable: false }, // 4. authority
      { pubkey: SystemProgram.programId, isSigner: false, isWritable: false }, // 5. system_program
    ],
    data,
  });
}

// ─── On-chain escrow account reader ──────────────────────────────────────────
//
// RentalEscrow memory layout (after 8-byte discriminator):
//   0..32  renter              Pubkey
//  32..64  agent_owner         Pubkey
//  64..72  amount_lamports     u64 LE
//  72..80  platform_fee_lamports u64 LE
//  80      status              u8 (0=Active 1=Completed 2=Refunded 3=Disputed)
//  81..89  nonce               [u8;8]
//  89      bump                u8
//  90      vault_bump          u8

export type EscrowAccount = {
  renter:               string;
  agentOwner:           string;
  amountLamports:       bigint;
  platformFeeLamports:  bigint;
  status:               "Active" | "Completed" | "Refunded" | "Disputed" | "Unknown";
  nonce:                Uint8Array;
  bump:                 number;
  vaultBump:            number;
};

const STATUS_MAP = ["Active", "Completed", "Refunded", "Disputed"] as const;

export async function fetchEscrowAccount(
  connection: Connection,
  escrowPubkey: PublicKey,
): Promise<EscrowAccount | null> {
  const info = await connection.getAccountInfo(escrowPubkey);
  if (!info || info.data.length < 91) return null;

  const d = info.data;
  const off = 8; // skip 8-byte discriminator

  return {
    renter:              new PublicKey(d.slice(off, off + 32)).toBase58(),
    agentOwner:          new PublicKey(d.slice(off + 32, off + 64)).toBase58(),
    amountLamports:      d.readBigUInt64LE(off + 64),
    platformFeeLamports: d.readBigUInt64LE(off + 72),
    status:              STATUS_MAP[d[off + 80]] ?? "Unknown",
    nonce:               d.slice(off + 81, off + 89),
    bump:                d[off + 89],
    vaultBump:           d[off + 90],
  };
}

// ─── Server-side: send complete_rental transaction ────────────────────────────
// Used by the expire-rentals cron job.

export async function sendCompleteRental(
  connection: Connection,
  programId: PublicKey,
  escrowPubkey: PublicKey,
  agentOwnerWallet: string,
  treasuryWallet: string,
  authorityKeypair: Keypair,
): Promise<string> {
  const ix = await buildCompleteRentalIx(
    programId,
    escrowPubkey,
    new PublicKey(agentOwnerWallet),
    new PublicKey(treasuryWallet),
    authorityKeypair.publicKey,
  );
  const tx = new Transaction().add(ix);
  return sendAndConfirmTransaction(connection, tx, [authorityKeypair], {
    commitment: "confirmed",
  });
}

// ─── Utility: load platform authority keypair from env ────────────────────────

export function loadAuthorityKeypair(): Keypair | null {
  const raw = process.env.PLATFORM_AUTHORITY_KEYPAIR;
  if (!raw) return null;
  try {
    const bytes = Uint8Array.from(JSON.parse(raw) as number[]);
    return Keypair.fromSecretKey(bytes);
  } catch {
    return null;
  }
}
